name: CI - CD @ postgres
on:
  push:
    branches:
      - DevOps
  pull_request:
    branches: 
      - DevOps
  workflow_call: 
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  deploy:
    #needs: build
    runs-on: ubuntu-latest
    env: 
      MODULE_NAME: postgres
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'padamkirankumar/postgres' 
          ref: DevOps       
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1          
      - name: helm deploy
        uses: netf/helm-eks-action@v1
        with:
          cluster-name: Kiran-K8S-Cluster
          command: helm upgrade --set image.tag="$GITHUB_SHA" --install ${{ env.MODULE_NAME }} ./helm-chart/${{ env.MODULE_NAME }}
